services:
  go_comics_rss:
    container_name: web-server-rss
    image: ghcr.io/tomasinjo/go-comics-rss:main
    restart: unless-stopped
    environment:
      # List of GoComics authors to fetch comics from
      - GO_COMICS_AUTHORS=clayjones,michaelramirez
      # Feed settings
      - FEED_DOMAIN=rss.example.com
      - FEED_MAX_AGE_DAYS=10            # maximum age of comics in the feed
      - FEED_INITIAL_FETCH_DAYS_BACK=3  # days bacl to start fetching comics from, optional
    volumes:
      - ./rss_data:/app/output  # rss feed and json are here

  web-server:
    container_name: web-server-rss
    image: joseluisq/static-web-server:2-alpine
    ports:
      - 8882:80
    restart: unless-stopped
    environment:
      - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ./rss_data/feed.rss:/var/www/rss/feed.rss
      - ./config.toml:/etc/config.toml